version: '3.9'
services:
  my-sql:
    image: mysql:8.0.32
    ports:
      - '3309:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs-typeorm
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
